spring:
  profiles:
    default: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(hrN+eQ4p84E3NW0vTIIRfhlAvKoNxPvYFvCAN2O9CyD7UZpSDS2dI9fEsBaHp6gftj+l4UOIBo5BHRIo2BQiC403lDFKj8I5ySiIxdvhY0Pp7fheX5J9DvJD5elcnAthagf+7EFdQVuQ0xdSODL7LceQs5DCSwESYThyL9HLPVM=)
    username: ENC(FTbbdqVBbcTrUysSwbf/BwFbE0HhgdyXT+Z0uC0xZfLyuftv/9ceA4wQdOp70vMT)
    password: ENC(7+z+f1IVvS1HcBCtH8hYpUMbEM6mcHVBw93co3jNIhp8EuXicXkee/MlqY1DkJq2)
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false