spring:
  profiles:
    default: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(lFITsL+l7aOSMUY3hRT3aR4X0GV+yqIJfYMyXaMajbZZJSW+Lv5MTrbP5Cwa8XAUxGpH7A9GxRNAZtrDhf6V4yXkD6gf3RUYWsPp77Ieguo=)
    username: ENC(s1UggVxVWnWC0WqrTpmXaLw+QCpZmkuj2kvSQp+zt2vwKLbRH6WDAZKYUR75DqsR)
    password: ENC(HT2z+x9LrfoHTmTTCYLkx7cO0ru9Gcbh+YGnP/0MWC1BpBwQtPfWue+zQx5RPQg8)

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false