spring:
  profiles:
    default: local
  config:
    import:
      - classpath:/application-domain.yml

witheang:
  auth:
    jwt-secret-key: ENC(1t2RYsNu8JCGgZjC5HuE9t9690mWUiygMhKfUQIn3ZpVlSYI0WvRPnQswh3Uti3gBoDqJ4Zk3moN6wWswWQC7g+IFiEDUvqjTLzhfJrl9A0TIW0MOY0kd+vnVu0sernJ)
    jwt-issuer: https://github.com/withaeng/withaeng-backend